# Generated by Django 5.0 on 2023-12-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('dia_da_falta', models.DateField()),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('conteudo', models.CharField(max_length=255)),
                ('concordo', models.BooleanField()),
            ],
        ),
    ]
