# Generated by Django 5.0 on 2023-12-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
