# Generated by Django 5.0 on 2023-12-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='curso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
