# Generated by Django 5.0 on 2023-12-27 23:46

import EmailMarketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0003_professor_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disponibilidade',
            field=models.JSONField(default=EmailMarketing.models.disponibilidade_padrao),
        ),
    ]
